version: "3"
services:

    app-passport:
      build: 
        context: ./api
        dockerfile: Dockerfile
      container_name: app
      restart: always
      depends_on:
        - mongo-passport
      ports:
       - '3000:3000'
      volumes:
        - ./api:/app/
        - '/app/node_modules'      
      environment:
        - NODE_ENV=development
      networks:
        - net      

    mongo-passport:
      image: mongo
      container_name: mongo
      restart: always
      environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: root
        MONGO_INITDB_DATABASE: passeport
      volumes:
        - ./mongodb/datas/:/docker-entrypoint-initdb.d/
      networks:
        - net

    mongo-express-passport:
      image: mongo-express
      container_name: mongo-express-passport
      restart: always
      ports:
        - 8081:8081
      depends_on:
        - mongo-passport
      environment:
        ME_CONFIG_MONGODB_ADMINUSERNAME: root
        ME_CONFIG_MONGODB_ADMINPASSWORD: root
      networks:
        - net

networks:
  net:
    driver: bridge
